"""
build_map.py  –  Reads province_paths.json (generated by generate_svg_paths.py)
and injects real SVG paths + etymology data into the final HTML interactive map.
Run with QGIS Python or any Python 3 interpreter.
"""

import sys, os, json
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

GEODATA_DIR = os.path.dirname(os.path.abspath(__file__))
PATHS_JSON  = os.path.join(GEODATA_DIR, "province_paths.json")
OUT_HTML    = os.path.join(GEODATA_DIR, "..", "sweden_provinces_map.html")

# ─── Etymology data for all 25 provinces ────────────────────────────────────
ETYMOLOGY = {
    "Skåne":         {"meaning": '"Scandinavia\'s Origin / Hazardous Shore"',
                      "etymology": "Linked to proto-Germanic *Skaðin-awjā, possibly from skaðan (damage/danger) — referring to the treacherous coastal sandbanks near Falsterbo. This same root gave rise to the name 'Scandinavia' itself."},
    "Blekinge":      {"meaning": '"The Shining / Pale Land"',
                      "etymology": "From Old Norse bleikr (pale, shining, whitish). Likely describing the glistening pale appearance of the sea and its light-reflecting coastline. Some scholars connect it to bleaching grounds along the shore."},
    "Öland":         {"meaning": '"Island Land"',
                      "etymology": "Simply ö (island) + land. Öland is a long, narrow island off Sweden's southeast coast — quite literally an island-land. Its unique limestone plain (alvar) is a UNESCO World Heritage Site."},
    "Halland":       {"meaning": '"Stony Slopes"',
                      "etymology": "From Old Norse hallr (slope, flat stone, rocky terrain). The name perfectly captures the hilly, rocky coastal landscape along the Kattegat sea."},
    "Småland":       {"meaning": '"Small Lands"',
                      "etymology": "Literally smá (small) + land (lands, plural). The province was historically a patchwork of several small independent territories — Värend, Finnveden, Njudung, and Möre — bundled together into one name."},
    "Gotland":       {"meaning": '"Land of the Gutar"',
                      "etymology": "Named after the Gutar (Gutes), the Norse tribe who inhabited the island. Gut-land = 'land of the Gutes.' The Gutar had their own unique law code, dialect, and identity, distinct from mainland Swedes, for centuries."},
    "Västergötland": {"meaning": '"West Gothland"',
                      "etymology": "Väster (west) + Göta (Geats) + land. The homeland of the western Götar (Geats) — the ancient tribe celebrated in the Old English epic Beowulf. Separated from Östergötland by Lake Vättern."},
    "Östergötland":  {"meaning": '"East Gothland"',
                      "etymology": "From Old Norse Austrgautland — öster (east) + Göta (Geats) + land. The eastern homeland of the Götar tribe, sharing the same roots as Västergötland but on the opposite side of Lake Vättern."},
    "Bohuslän":      {"meaning": '"District of Bohus Fortress"',
                      "etymology": "Named after the medieval fortress Bohus fästning (bo = dweller, hus = house/fortress). The province was the land belonging to and defended by this strategic fortress at the confluence of the Göta and Nordre rivers."},
    "Dalsland":      {"meaning": '"Valley Land"',
                      "etymology": "From dal (valley) + land. The province is defined by deep, forested valleys and river gorges, alongside a patchwork of lakes — the geography directly inspired the name."},
    "Närke":         {"meaning": '"The Narrow One"',
                      "etymology": "From Old Swedish når or nar (narrow). The name likely describes a narrow ridge or geographic feature. Also associated with the ancient Njarar tribe — 'the people of the narrows.'"},
    "Södermanland":  {"meaning": '"Land of the Southern Men"',
                      "etymology": "Söder (south) + man (men) + land. The södermän were the people living south of the Mälaren lake basin and Uppland — distinguished as the southern folk relative to the Svear core homeland."},
    "Värmland":      {"meaning": '"Land of the Warm-River Folk"',
                      "etymology": "Named after the Värmar tribe. Their name likely derives from the river Värman (now Borgviksälven), known for swift, warm water that never froze. Varm means warm in Swedish."},
    "Västmanland":   {"meaning": '"Land of the Western Men"',
                      "etymology": "Väster (west) + man (men) + land. The västmän were the people living west of the Uppland heartland — the western counterpart to those of the Svear core lands around Lake Mälaren."},
    "Uppland":       {"meaning": '"The Up-Land"',
                      "etymology": "Upp (up/upper) + land. The heartland and cradle of ancient Sweden — Uppsala, the sacred royal city, lies here. The name reflects both geographic elevation and supreme political status as the Svear kingdom's core."},
    "Gästrikland":   {"meaning": '"Land of the Guests"',
                      "etymology": "First recorded in 1253 as Gestrikalandia. Likely from gäst (guest/stranger) — referring to settlers or newcomers (gästar) who moved into the territory from elsewhere. Acts as a gateway to the north."},
    "Dalarna":       {"meaning": '"The Valleys"',
                      "etymology": "Dalarna is simply the plural of dal (valley). The province is sculpted by the great river valleys of the Österdalälven and Västerdalälven. The Dala horse — Sweden's most iconic folk art — originates here."},
    "Hälsingland":   {"meaning": '"Land of the Neck-Dwellers"',
                      "etymology": "Named after the Hälsingar tribe, whose name links to hals (neck/strait). The people living by the narrow coastal straits. Fascinatingly, 'Hälsingar' is also the etymological root of Helsinki."},
    "Härjedalen":    {"meaning": '"Valley of the Härje River"',
                      "etymology": "Härje (from the river Härjeån, meaning 'lord's river') + dalen (the valley). A geographic name: the dramatic valley carved by the Härje river through alpine terrain."},
    "Medelpad":      {"meaning": '"Middle Path"',
                      "etymology": "From medel (middle) + pad (path/way). The province sits between the rivers Ljungan and Indalsälven — two great waterways used as ancient travel routes. A land literally lying 'between the paths.'"},
    "Ångermanland":  {"meaning": '"Land of the Narrow Fjords"',
                      "etymology": "From Old Norse angr (narrow bay, fjord, inlet) + man (people) + land. The spectacular river gorges and fjord-like inlets of the Ångerman River carve this province's dramatic landscape."},
    "Jämtland":      {"meaning": '"Land of the Jämtar People"',
                      "etymology": "Named after the Jämtar tribe. Their name may derive from an Old Norse word for endurance or tenacity — fitting for the mountain folk who survived the harsh Scandinavian interior."},
    "Västerbotten":  {"meaning": '"West Bothnian Region"',
                      "etymology": "Väster (west) + Botten (bottom of the bay). 'Botten' refers to the Gulf of Bothnia — the northernmost, deepest extension of the Baltic Sea. This is the western shore of that bay."},
    "Lappland":      {"meaning": '"Land of the Sámi People"',
                      "etymology": "From Lapp (historical Swedish term for the Sámi indigenous people) + land. The vast wilderness of Swedish Lapland is the ancient homeland of the Sámi — reindeer herders of the Arctic with a culture stretching back millennia."},
    "Norrbotten":    {"meaning": '"North Bothnian Region"',
                      "etymology": "Norr (north) + Botten (bottom of the bay). The northernmost Swedish province — at the very top of the Gulf of Bothnia. Larger than many European countries, it borders both Norway and Finland."},
}

# ─── Region colors ────────────────────────────────────────────────────────────
REGION_COLORS = {
    1: {"base": "#2d6e45", "hover": "#3d8e5a"},   # Götaland — green
    2: {"base": "#264e7a", "hover": "#3665a0"},   # Svealand  — blue
    3: {"base": "#6b3522", "hover": "#8b4530"},   # Norrland  — warm brown
}

# ─── Load paths ───────────────────────────────────────────────────────────────
with open(PATHS_JSON, encoding="utf-8") as f:
    data = json.load(f)

viewBox = data["viewBox"]

# Build province JS objects
js_provinces = []
for p in data["provinces"]:
    name = p["name"]
    etym = ETYMOLOGY.get(name, {"meaning": "Unknown", "etymology": "Not available"})
    rcode = p["landsdelskod"]
    col   = REGION_COLORS.get(rcode, {"base": "#555"})["base"]
    obj = {
        "id":         p["id"],
        "name":       name,
        "landsdel":   p["landsdel"],
        "landsdelskod": rcode,
        "color":      col,
        "cx":         p["cx"],
        "cy":         p["cy"],
        "path":       p["path"],
        "meaning":    etym["meaning"],
        "etymology":  etym["etymology"],
    }
    js_provinces.append(obj)

provinces_json = json.dumps(js_provinces, ensure_ascii=False, indent=4)

# ─── Generate HTML ────────────────────────────────────────────────────────────
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <title>Swedish Provinces — Literal Name Meanings</title>
  <meta name="description" content="An interactive map of Sweden's 25 historical provinces (landskap) with accurate geographic boundaries from Lantmäteriet, showing the literal etymological meanings of their names."/>
  <link rel="preconnect" href="https://fonts.googleapis.com"/>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Playfair+Display:ital,wght@0,600;1,500&display=swap" rel="stylesheet"/>
  <style>
    *,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
    :root{{
      --bg:#0d1117;--surface:#161b22;--surface2:#21262d;--border:#30363d;
      --accent:#58a6ff;--accent2:#79c0ff;--gold:#e3b341;
      --text:#e6edf3;--muted:#8b949e;
    }}
    body{{font-family:'Outfit',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden}}

    header{{text-align:center;padding:1.8rem 1rem 0.4rem}}
    header::after{{content:'';display:block;width:70px;height:3px;
      background:linear-gradient(90deg,var(--accent),var(--gold));
      margin:.7rem auto 0;border-radius:2px}}
    h1{{font-family:'Playfair Display',serif;font-size:clamp(1.7rem,3.5vw,2.6rem);
      background:linear-gradient(135deg,#e6edf3 30%,var(--gold) 100%);
      -webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}}
    .sub{{font-size:.92rem;color:var(--muted);margin-top:.3rem;font-weight:300}}

    .legend{{display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;
      padding:.6rem 1rem 0;font-size:.78rem;color:var(--muted)}}
    .li{{display:flex;align-items:center;gap:.4rem}}
    .ld{{width:11px;height:11px;border-radius:3px}}

    .stats{{display:flex;gap:.7rem;justify-content:center;flex-wrap:wrap;
      padding:.5rem 1rem .3rem}}
    .stat{{background:var(--surface);border:1px solid var(--border);border-radius:9px;
      padding:.4rem .9rem;text-align:center;font-size:.76rem;color:var(--muted)}}
    .stat strong{{display:block;font-size:1.1rem;color:var(--text);font-weight:600}}

    .layout{{display:grid;grid-template-columns:1fr 350px;gap:1.1rem;
      max-width:1280px;margin:1rem auto 2rem;padding:0 1.1rem}}
    @media(max-width:860px){{.layout{{grid-template-columns:1fr}}}}

    /* MAP */
    .map-wrap{{background:var(--surface);border:1px solid var(--border);
      border-radius:16px;overflow:hidden;position:relative;
      min-height:600px;display:flex;align-items:center;justify-content:center}}
    #map{{width:100%;height:100%;max-height:850px;cursor:grab}}
    #map:active{{cursor:grabbing}}

    .zctrl{{position:absolute;top:10px;right:10px;display:flex;flex-direction:column;gap:4px;z-index:10}}
    .zb{{width:30px;height:30px;background:var(--surface2);border:1px solid var(--border);
      border-radius:7px;color:var(--text);font-size:1rem;cursor:pointer;
      display:flex;align-items:center;justify-content:center;transition:border-color .2s}}
    .zb:hover{{border-color:var(--accent)}}

    .hint{{position:absolute;bottom:10px;left:50%;transform:translateX(-50%);
      font-size:.72rem;color:var(--muted);background:rgba(13,17,23,.85);
      padding:.22rem .7rem;border-radius:20px;border:1px solid var(--border);
      white-space:nowrap;pointer-events:none}}

    /* Provinces */
    .prov{{cursor:pointer;stroke:rgba(255,255,255,.12);stroke-width:.4;
      transition:filter .18s,opacity .18s}}
    .prov:hover{{filter:brightness(1.4) drop-shadow(0 0 5px rgba(88,166,255,.6));
      stroke:rgba(121,192,255,.85);stroke-width:.7}}
    .prov.active{{filter:brightness(1.55) drop-shadow(0 0 8px rgba(227,179,65,.85));
      stroke:var(--gold)!important;stroke-width:1!important}}
    .prov.dim{{opacity:.38}}
    .plbl{{font-family:'Outfit',sans-serif;font-size:6px;fill:rgba(255,255,255,.6);
      text-anchor:middle;dominant-baseline:middle;pointer-events:none;user-select:none}}

    /* SIDEBAR */
    .sidebar{{display:flex;flex-direction:column;gap:1rem}}
    .dcard{{background:var(--surface);border:1px solid var(--border);border-radius:16px;
      padding:1.35rem;min-height:250px;position:relative;overflow:hidden;transition:border-color .3s}}
    .dcard::before{{content:'';position:absolute;top:0;left:0;right:0;height:3px;
      background:linear-gradient(90deg,var(--accent),var(--gold));
      transform:scaleX(0);transform-origin:left;transition:transform .4s;
      border-radius:16px 16px 0 0}}
    .dcard.on::before{{transform:scaleX(1)}}
    .dcard.on{{border-color:rgba(88,166,255,.25)}}

    .ph{{display:flex;flex-direction:column;align-items:center;justify-content:center;
      height:100%;gap:.7rem;color:var(--muted);text-align:center}}
    .ph-icon{{font-size:2.6rem;opacity:.28}}
    .ph p{{font-size:.86rem;max-width:185px;line-height:1.55}}

    .pname{{font-family:'Playfair Display',serif;font-size:1.7rem;color:var(--text);margin-bottom:.18rem}}
    .rtag{{display:inline-block;font-size:.68rem;font-weight:600;letter-spacing:.8px;
      text-transform:uppercase;padding:.16rem .6rem;border-radius:20px;margin-bottom:.85rem}}
    .rg1{{background:rgba(45,110,69,.35);color:#6fcf97;border:1px solid rgba(45,110,69,.6)}}
    .rg2{{background:rgba(38,78,122,.35);color:#79c0ff;border:1px solid rgba(38,78,122,.6)}}
    .rg3{{background:rgba(107,53,34,.35);color:#ffab70;border:1px solid rgba(107,53,34,.6)}}

    .mblk{{background:var(--surface2);border-radius:9px;padding:.85rem 1rem;
      margin:.65rem 0;border-left:3px solid var(--gold)}}
    .ml{{font-size:.67rem;text-transform:uppercase;letter-spacing:1px;color:var(--gold);font-weight:600;margin-bottom:.28rem}}
    .mv{{font-size:1.15rem;font-family:'Playfair Display',serif;font-style:italic;color:var(--text)}}
    .etl{{font-size:.67rem;text-transform:uppercase;letter-spacing:1px;color:var(--muted);font-weight:600;
      margin:.75rem 0 .3rem}}
    .ete{{font-size:.84rem;color:#c9d1d9;line-height:1.65}}

    /* List */
    .lcard{{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:.85rem;flex:1}}
    .lhdr{{font-size:.7rem;text-transform:uppercase;letter-spacing:1px;color:var(--muted);
      font-weight:600;padding-bottom:.55rem;border-bottom:1px solid var(--border);margin-bottom:.45rem}}
    .srch{{width:100%;background:var(--surface2);border:1px solid var(--border);border-radius:8px;
      padding:.4rem .7rem;color:var(--text);font-family:'Outfit',sans-serif;font-size:.82rem;
      margin-bottom:.45rem;outline:none;transition:border-color .2s}}
    .srch:focus{{border-color:var(--accent)}}
    .srch::placeholder{{color:var(--muted)}}
    .plist{{list-style:none;max-height:290px;overflow-y:auto;
      scrollbar-width:thin;scrollbar-color:var(--border) transparent}}
    .plist li{{display:flex;align-items:center;gap:.5rem;padding:.38rem .42rem;
      border-radius:7px;cursor:pointer;font-size:.81rem;transition:background .12s}}
    .plist li:hover{{background:var(--surface2)}}
    .plist li.sel{{background:rgba(88,166,255,.1);color:var(--accent2)}}
    .ldot{{width:8px;height:8px;border-radius:50%;flex-shrink:0}}
    .lmean{{font-size:.69rem;color:var(--muted);margin-left:auto;max-width:125px;
      overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:right}}

    /* Tooltip */
    #tt{{position:fixed;background:rgba(22,27,34,.96);border:1px solid var(--accent);
      border-radius:10px;padding:.52rem .88rem;pointer-events:none;z-index:9999;
      opacity:0;transform:translateY(4px);transition:opacity .14s,transform .14s;
      max-width:205px;backdrop-filter:blur(8px)}}
    #tt.on{{opacity:1;transform:translateY(0)}}
    .tn{{font-weight:600;font-size:.9rem;color:var(--text)}}
    .tm{{font-size:.78rem;color:var(--gold);font-style:italic;margin-top:.07rem}}

    /* Data credit */
    .credit{{text-align:center;padding:.4rem 1rem 1.2rem;font-size:.7rem;color:var(--muted)}}
    .credit a{{color:var(--accent);text-decoration:none}}
    .credit a:hover{{text-decoration:underline}}
  </style>
</head>
<body>
<header>
  <h1>Swedish Provinces</h1>
  <p class="sub">Hover or click a province to reveal the literal meaning of its name</p>
</header>
<div class="legend">
  <div class="li"><div class="ld" style="background:#2d6e45"></div>Götaland — Land of the Geats</div>
  <div class="li"><div class="ld" style="background:#264e7a"></div>Svealand — Land of the Svear</div>
  <div class="li"><div class="ld" style="background:#6b3522"></div>Norrland — Northern Land</div>
</div>
<div class="stats">
  <div class="stat"><strong>25</strong>Provinces</div>
  <div class="stat"><strong>~1000 yrs</strong>of names</div>
  <div class="stat"><strong>3</strong>Great regions</div>
</div>
<div class="layout">
  <div class="map-wrap">
    <div class="zctrl">
      <button class="zb" id="zi">+</button>
      <button class="zb" id="zo">−</button>
      <button class="zb" id="zr" style="font-size:.7rem">↺</button>
    </div>
    <svg id="map" viewBox="{viewBox}" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <radialGradient id="bg" cx="50%" cy="50%" r="70%">
          <stop offset="0%" stop-color="#1a2235"/>
          <stop offset="100%" stop-color="#0d1117"/>
        </radialGradient>
      </defs>
      <rect width="500" height="900" fill="url(#bg)"/>
      <g id="pg"></g>
    </svg>
    <span class="hint">🖱 Hover to preview · Click to explore · Scroll to zoom</span>
  </div>
  <div class="sidebar">
    <div class="dcard" id="dc">
      <div class="ph" id="ph">
        <div class="ph-icon">🗺️</div>
        <p>Click a province on the map to discover the literal meaning of its name</p>
      </div>
      <div id="di" style="display:none">
        <div class="pname" id="dn"></div>
        <span class="rtag" id="dr"></span>
        <div class="mblk">
          <div class="ml">Literal Meaning</div>
          <div class="mv" id="dm"></div>
        </div>
        <div class="etl">Etymology</div>
        <div class="ete" id="de"></div>
      </div>
    </div>
    <div class="lcard">
      <div class="lhdr">All 25 Provinces</div>
      <input class="srch" id="srch" type="search" placeholder="Search provinces…"/>
      <ul class="plist" id="pl"></ul>
    </div>
  </div>
</div>
<div class="credit">
  Geographic data: <a href="https://github.com/perliedman/svenska-landskap" target="_blank">perliedman/svenska-landskap</a>
  (Lantmäteriet, CC0) · Processed with QGIS 3.44 GDAL/OGR, SWEREF99 TM projection
</div>
<div id="tt"><div class="tn" id="ttn"></div><div class="tm" id="ttm"></div></div>

<script>
const PROVS = {provinces_json};

const REGIONS = {{
  1: {{label:'Götaland',cls:'rg1',dot:'#2d6e45'}},
  2: {{label:'Svealand', cls:'rg2',dot:'#264e7a'}},
  3: {{label:'Norrland', cls:'rg3',dot:'#6b3522'}}
}};

let sel=null, sc=1, tx=0, ty=0, drag=false, ds={{x:0,y:0}};
const pg=document.getElementById('pg');
const svg=document.getElementById('map');

PROVS.forEach(p=>{{
  const path=document.createElementNS('http://www.w3.org/2000/svg','path');
  path.setAttribute('d',p.path);
  path.setAttribute('fill',p.color);
  path.setAttribute('id','p-'+p.id);
  path.classList.add('prov');
  path.dataset.id=p.id;
  const txt=document.createElementNS('http://www.w3.org/2000/svg','text');
  txt.setAttribute('x',p.cx); txt.setAttribute('y',p.cy);
  txt.classList.add('plbl');
  txt.textContent=p.name;
  pg.appendChild(path); pg.appendChild(txt);
  path.addEventListener('mouseenter',e=>showTT(e,p));
  path.addEventListener('mousemove',moveTT);
  path.addEventListener('mouseleave',hideTT);
  path.addEventListener('click',()=>selP(p.id));
}});

const pl=document.getElementById('pl');
const srch=document.getElementById('srch');
function renderList(q=''){{
  pl.innerHTML='';
  const lq=q.toLowerCase();
  PROVS.filter(p=>p.name.toLowerCase().includes(lq)||p.meaning.toLowerCase().includes(lq))
    .forEach(p=>{{
      const li=document.createElement('li');
      if(p.id===sel)li.classList.add('sel');
      const dot=document.createElement('span'); dot.className='ldot';
      dot.style.background=REGIONS[p.landsdelskod].dot;
      const nm=document.createElement('span'); nm.textContent=p.name;
      const mn=document.createElement('span'); mn.className='lmean';
      mn.textContent=p.meaning.replace(/"/g,'');
      li.append(dot,nm,mn);
      li.addEventListener('click',()=>selP(p.id));
      pl.appendChild(li);
    }});
}}
srch.addEventListener('input',()=>renderList(srch.value));
renderList();

function selP(id){{
  sel=id;
  const p=PROVS.find(x=>x.id===id); if(!p)return;
  PROVS.forEach(pv=>{{
    const el=document.getElementById('p-'+pv.id);
    el.classList.remove('active','dim');
    el.classList.add(pv.id===id?'active':'dim');
  }});
  const dc=document.getElementById('dc');
  dc.classList.add('on');
  document.getElementById('ph').style.display='none';
  document.getElementById('di').style.display='block';
  document.getElementById('dn').textContent=p.name;
  const rt=document.getElementById('dr');
  const rm=REGIONS[p.landsdelskod];
  rt.textContent=rm.label; rt.className='rtag '+rm.cls;
  document.getElementById('dm').textContent=p.meaning;
  document.getElementById('de').textContent=p.etymology;
  renderList(srch.value);
  const li=pl.querySelector(`[data-id="${{id}}"]`);
  // find correct li by checking its text
  [...pl.querySelectorAll('li')].forEach(l=>{{
    if(l.querySelector('span:nth-child(2)')?.textContent===p.name)
      l.scrollIntoView({{block:'nearest',behavior:'smooth'}});
  }});
}}

const tt=document.getElementById('tt');
function showTT(e,p){{
  document.getElementById('ttn').textContent=p.name;
  document.getElementById('ttm').textContent=p.meaning;
  tt.classList.add('on'); moveTT(e);
}}
function moveTT(e){{
  const x=e.clientX+14,y=e.clientY-10;
  tt.style.left=Math.min(x,window.innerWidth-tt.offsetWidth-8)+'px';
  tt.style.top=Math.max(y,8)+'px';
}}
function hideTT(){{tt.classList.remove('on');}}

function applyT(){{pg.setAttribute('transform',`translate(${{tx}},${{ty}}) scale(${{sc}})`);}}
document.getElementById('zi').onclick=()=>{{sc=Math.min(sc*1.3,10);applyT();}};
document.getElementById('zo').onclick=()=>{{sc=Math.max(sc/1.3,.3);applyT();}};
document.getElementById('zr').onclick=()=>{{sc=1;tx=0;ty=0;applyT();}};

svg.addEventListener('mousedown',e=>{{
  if(e.target.classList.contains('prov'))return;
  drag=true; ds={{x:e.clientX-tx,y:e.clientY-ty}};
}});
window.addEventListener('mousemove',e=>{{if(!drag)return;tx=e.clientX-ds.x;ty=e.clientY-ds.y;applyT();}});
window.addEventListener('mouseup',()=>{{drag=false;}});

svg.addEventListener('wheel',e=>{{
  e.preventDefault();
  const d=e.deltaY<0?1.15:.87;
  const rect=svg.getBoundingClientRect();
  const [vx,vy,vw,vh]=[0,0,500,900];
  const mx=(e.clientX-rect.left)/rect.width*vw;
  const my=(e.clientY-rect.top)/rect.height*vh;
  sc=Math.min(Math.max(sc*d,.3),10);
  tx=mx-(mx-tx)*d; ty=my-(my-ty)*d; applyT();
}},{{passive:false}});

let ltd=null;
svg.addEventListener('touchstart',e=>{{
  if(e.touches.length===2)
    ltd=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);
}});
svg.addEventListener('touchmove',e=>{{
  if(e.touches.length===2&&ltd){{
    e.preventDefault();
    const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);
    sc=Math.min(Math.max(sc*d/ltd,.3),10); applyT(); ltd=d;
  }}
}},{{passive:false}});
</script>
</body>
</html>"""

with open(OUT_HTML, "w", encoding="utf-8") as f:
    f.write(html)

print(f"HTML map written to:\n  {OUT_HTML}")
print(f"Provinces embedded: {len(data['provinces'])}")
